export const publicRoutes = [
    '/users/login',
    '/users/registration',
    '/public',
    '/',
    '/captcha',
    '/verify/:username/:token',
    '/users/verification',
    '/auth/vk',
    '/auth/discord',
    '/auth/github',
    '/auth/google',
    '/auth/discord/callback',
    '/auth/github/callback',
    '/auth/google/callback',
    '/auth/vk/callback',
    '/auth/callback',
    '/get-user-keys'
];